//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by vh_co at LAPTOP-AI0568T3 on 12/18/2020 16:01:56 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using ONC.RESTful.Entities;

namespace ONC.RESTful.Data
{

    /// <summary>
    /// Feriado data access component. Manages CRUD operations for the Feriado table.
    /// </summary>
    public partial class FeriadoDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the Feriado table.
        /// </summary>
        /// <param name="feriado">A Feriado object.</param>
        /// <returns>An updated Feriado object.</returns>
        public Feriado Create(Feriado feriado)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.Feriado ([dia], [mes], [ano], [tipo], [fecha]) " +
                "VALUES(@dia, @mes, @ano, @tipo, @fecha); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            var db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@dia", DbType.Int32, feriado.dia);
                db.AddInParameter(cmd, "@mes", DbType.Int32, feriado.mes);
                db.AddInParameter(cmd, "@ano", DbType.Int32, feriado.ano);
                db.AddInParameter(cmd, "@tipo", DbType.AnsiString, feriado.tipo);
                db.AddInParameter(cmd, "@fecha", DbType.DateTime, feriado.fecha);

                // Get the primary key value.
                feriado.id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return feriado;
        }

        /// <summary>
        /// Updates an existing row in the Feriado table.
        /// </summary>
        /// <param name="feriado">A Feriado entity object.</param>
        public void UpdateById(Feriado feriado)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.Feriado " +
                "SET " +
                    "[dia]=@dia, " +
                    "[mes]=@mes, " +
                    "[ano]=@ano, " +
                    "[tipo]=@tipo, " +
                    "[fecha]=@fecha " +
                "WHERE [id]=@id ";

            // Connect to database.
            var db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@dia", DbType.Int32, feriado.dia);
                db.AddInParameter(cmd, "@mes", DbType.Int32, feriado.mes);
                db.AddInParameter(cmd, "@ano", DbType.Int32, feriado.ano);
                db.AddInParameter(cmd, "@tipo", DbType.AnsiString, feriado.tipo);
                db.AddInParameter(cmd, "@fecha", DbType.DateTime, feriado.fecha);
                db.AddInParameter(cmd, "@id", DbType.Int32, feriado.id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the Feriado table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.Feriado " +
                                         "WHERE [id]=@id ";

            // Connect to database.
            var db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the Feriado table.
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>A Feriado object with data populated from the database.</returns>
        public Feriado SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [id], [dia], [mes], [ano], [tipo], [fecha] " +
                "FROM dbo.Feriado  " +
                "WHERE [id]=@id ";

            Feriado feriado = null;

            // Connect to database.
            var db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new Feriado
                        feriado = LoadFeriado(dr);
                    }
                }
            }

            return feriado;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the Feriado table.
        /// </summary>
        /// <returns>A collection of Feriado objects.</returns>		
        public List<Feriado> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [id], [dia], [mes], [ano], [tipo], [fecha] " +
                "FROM dbo.Feriado ";

            List<Feriado> result = new List<Feriado>();

            // Connect to database.
            var db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new Feriado
                        Feriado feriado = LoadFeriado(dr);

                        // Add to List.
                        result.Add(feriado);
                    }
                }
            }

            return result;
        }

        /// <summary>
        /// Creates a new Feriado from a Datareader.
        /// </summary>
        /// <param name="dr">A DataReader object.</param>
        /// <returns>Returns a Feriado.</returns>		
        private Feriado LoadFeriado(IDataReader dr)
        {
            // Create a new Feriado
            Feriado feriado = new Feriado();

            // Read values.
            feriado.id = GetDataValue<int>(dr, "id");
            feriado.dia = GetDataValue<int>(dr, "dia");
            feriado.mes = GetDataValue<int>(dr, "mes");
            feriado.ano = GetDataValue<int>(dr, "ano");
            feriado.tipo = GetDataValue<string>(dr, "tipo");
            feriado.fecha = GetDataValue<DateTime>(dr, "fecha");

            return feriado;
        }
    }
}

