//====================================================================================================
// Base code generated with Relativity: HTTP Service Controller Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by vh_co at LAPTOP-AI0568T3 on 12/18/2020 16:13:00 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ONC.RESTful.Business;
using ONC.RESTful.Entities;

namespace ONC.RESTful.Services.Http
{
    /// <summary>
    /// Feriado HTTP service controller.
    /// </summary>
    [RoutePrefix("api/Feriado")]
    public class FeriadoService : ApiController
    {
        /// <summary>
        /// Calls the Add business method of the FeriadoComponent.
        /// </summary>
        /// <param name="feriado"> A feriado value.</param>
        /// <returns>Returns a Feriado object.</returns>
        [HttpPost]
        [Route("")]
        public Feriado Add(Feriado feriado)
        {
            try
            {
                var bc = new FeriadoComponent();
                return bc.Add(feriado);
            }
            catch (Exception ex)
            {
                // Repack to Http error.
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        /// <summary>
        /// Calls the Edit business method of the FeriadoComponent.
        /// </summary>
        /// <param name="feriado"> A feriado value.</param>
        [HttpPut]
        [Route("")]
        public void Edit(Feriado feriado)
        {
            try
            {
                var bc = new FeriadoComponent();
                bc.Edit(feriado);
            }
            catch (Exception ex)
            {
                // Repack to Http error.
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        /// <summary>
        /// Calls the Find business method of the FeriadoComponent.
        /// </summary>
        /// <param name="id"> A id value.</param>
        /// <returns>Returns a Feriado object.</returns>
        [HttpGet]
        [Route("{id}")]
        public Feriado Find(int id)
        {
            try
            {
                var bc = new FeriadoComponent();
                return bc.Find(id);
            }
            catch (Exception ex)
            {
                // Repack to Http error.
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        /// <summary>
        /// Calls the Remove business method of the FeriadoComponent.
        /// </summary>
        /// <param name="id"> A id value.</param>
        [HttpDelete]
        [Route("")]
        public void Remove(int id)
        {
            try
            {
                var bc = new FeriadoComponent();
                bc.Remove(id);
            }
            catch (Exception ex)
            {
                // Repack to Http error.
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }

        /// <summary>
        /// Calls the Select business method of the FeriadoComponent.
        /// </summary>
        /// <returns>Returns a List<Feriado> object.</returns>
        [HttpGet]
        [Route("")]
        public List<Feriado> Select()
        {
            try
            {
                var bc = new FeriadoComponent();
                return bc.Select();
            }
            catch (Exception ex)
            {
                // Repack to Http error.
                var httpError = new HttpResponseMessage()
                {
                    StatusCode = (HttpStatusCode)422,
                    ReasonPhrase = ex.Message
                };

                throw new HttpResponseException(httpError);
            }
        }
    }
}

