//====================================================================================================
// Base code generated with Motion: BC Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by vh_co at LAPTOP-AI0568T3 on 12/22/2020 15:50:36 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ONC.RESTful.Entities;
using ONC.RESTful.Data;


namespace ONC.RESTful.Business
{
    /// <summary>
    /// Historico business component.
    /// </summary>
    public partial class HistoricoComponent
    {
        /// <summary>
        /// Select business method. 
        /// </summary>
        /// <param name="maximumRows"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="sortExpression"></param>
        /// <returns></returns>
        public List<Historico> Select(int maximumRows, int startRowIndex, string sortExpression)
        {
            List<Historico> result = default(List<Historico>);

            // Data access component declarations.
            var historicoDAC = new HistoricoDAC();

            // Step 1 - Calling SelectPageSort on HistoricoDAC.
            result = historicoDAC.SelectPageSort(maximumRows, startRowIndex, sortExpression);
            return result;

        }

        /// <summary>
        /// Find business method. 
        /// </summary>
        /// <param name="currentPage">A currentPage value.</param>
        /// <returns>Returns a List<Historico> object.</returns>
        public List<Historico> Find(int currentPage)
        {
            List<Historico> result = default(List<Historico>);

            // Data access component declarations.
            var historicoDAC = new HistoricoDAC();

            // Step 1 - Calling SelectPage on HistoricoDAC.
            result = historicoDAC.SelectPage(currentPage);
            return result;

        }
    }
}
